import type { Metadata } from 'next'
import { DocsPage, FieldTable, ObjectLabel } from '../_components'

export const metadata: Metadata = { title: 'Reliability | OddsLoom API', description: 'Draft ordering, timing, state transitions, and recovery behavior for OddsLoom.' }

export default function ReliabilityPage() {
  return <DocsPage current="/docs/reliability" title="Detect gaps. Recover cleanly." lede="A fast feed is only useful if consumers can prove their state is current. The proposed recovery model favors explicit gaps and deterministic reconstruction over silent continuation.">
    <section><ObjectLabel>ORDERING</ObjectLabel><h2>Sequence ownership</h2><p>The current proposal assigns a strictly increasing sequence to a subscription stream. Consumers commit a sequence only after its message has been applied durably.</p><div className="spec-grid"><div><span>Expected next</span><p>Apply when the sequence equals the last committed value plus one.</p></div><div><span>Duplicate</span><p>Ignore an already committed message ID or sequence.</p></div><div><span>Gap</span><p>Pause application and begin recovery immediately.</p></div><div><span>Resnapshot</span><p>Atomically replace state when replay is unavailable.</p></div></div></section>
    <section><ObjectLabel>DELIVERY</ObjectLabel><h2>Proposed guarantee</h2><p>The conservative beta target is <strong>ordered, at-least-once delivery</strong> within one subscription. Consumers must therefore be idempotent. Exactly-once delivery will not be claimed merely because replay exists.</p><FieldTable rows={[["message_id","deduplication","Safe identifier for repeated delivery of the same message."],["sequence","ordering","Determines application order inside the subscription."],["subscription_id","ownership","Prevents state from different subscriptions being combined."],["schema_version","compatibility","Selects the decoder and validation rules."]]} /></section>
    <section><ObjectLabel>TIME</ObjectLabel><h2>Four different clocks</h2><FieldTable rows={[["source_updated_at","RFC 3339?","When the upstream provider says its state changed, if supplied."],["observed_at","RFC 3339","When OddsLoom observed the provider state."],["emitted_at","RFC 3339","When OddsLoom emitted the normalized message."],["consumer_received_at","client clock","When your system received the frame; recorded by the consumer."]]} /><p>Use sequence for ordering. Use timestamps for freshness and latency analysis. Provider clocks may be absent or skewed.</p></section>
    <section><ObjectLabel>STATE</ObjectLabel><h2>Quote availability</h2><div className="state-lanes"><div><b>OPEN</b><span>Quote may be consumed as current.</span></div><i>→</i><div><b>SUSPENDED</b><span>Retain the last quote but treat it as unavailable.</span></div><i>→</i><div><b>OPEN</b><span>The same quote ID may reopen with replacement state.</span></div></div><div className="state-lanes"><div><b>OPEN</b><span>Current offer exists.</span></div><i>→</i><div><b>CLOSED</b><span>Market or event reached a terminal condition.</span></div><i>→</i><div><b>REMOVED</b><span>Delete after an explicit odds.remove.</span></div></div></section>
    <section><ObjectLabel>RECOVERY</ObjectLabel><h2>Gap procedure</h2><div className="flow-row"><span>GAP DETECTED</span><i>→</i><span>PAUSE DELTAS</span><i>→</i><span>REQUEST REPLAY</span><i>or</i><span>RESNAPSHOT</span><i>→</i><span>COMMIT</span><i>→</i><span>RESUME</span></div><ol><li>Stop mutating consumer-visible state.</li><li>Request recovery from the last durably committed sequence.</li><li>Apply replay in order, or atomically replace state with a new snapshot.</li><li>Resume only when the stream is contiguous again.</li></ol></section>
    <section><ObjectLabel>OPERATIONS / UNSET</ObjectLabel><h2>Limits still to publish</h2><p>These values must be measured and enforced before beta rather than invented in documentation.</p><div className="payload-matrix"><div><code>heartbeat interval</code><span>Maximum expected silence before a connection is considered unhealthy.</span><b>TBD</b></div><div><code>replay window</code><span>How long committed messages remain recoverable.</span><b>TBD</b></div><div><code>message size</code><span>Maximum encoded snapshot and delta frame size.</span><b>TBD</b></div><div><code>slow consumer</code><span>Buffer allowance and close behavior under backpressure.</span><b>TBD</b></div><div><code>connections</code><span>Concurrent sessions and subscriptions per credential.</span><b>TBD</b></div></div></section>
    <section className="docs-cta"><span className="section-kicker">Design review</span><h2>Tell us where this breaks.</h2><p>We want concrete feedback about sequence scope, recovery, market identity, and state transitions before the contract hardens.</p><a className="button primary" href="/beta">Request beta access →</a></section>
  </DocsPage>
}
