import type { Metadata } from 'next'
import { DocsPage, FieldTable, ObjectLabel } from '../_components'

export const metadata: Metadata = { title: 'Reliability | OddsLoom API', description: 'Beta-0 ordering, freshness, state transitions, and fresh-snapshot recovery behavior for OddsLoom.' }

export default function ReliabilityPage() {
  return <DocsPage current="/docs/reliability" title="Detect gaps. Recover from a fresh snapshot." lede="A fast feed is only useful if consumers can prove their state is current. Beta-0 favors explicit gaps and deterministic reconstruction over silent continuation: reconnects and sequence gaps require a new REST snapshot before deltas resume.">
    <section><ObjectLabel>ORDERING</ObjectLabel><h2>Sequence ownership</h2><p>Each subscription has an explicit effective scope and a strictly increasing sequence. Consumers commit a sequence only after its message has been applied durably.</p><div className="spec-grid"><div><span>Expected next</span><p>Apply when the sequence equals the last committed value plus one.</p></div><div><span>Duplicate</span><p>Ignore an already committed message ID or sequence.</p></div><div><span>Gap</span><p>Pause application and begin fresh-snapshot recovery immediately.</p></div><div><span>Fresh snapshot</span><p>Atomically replace state before any later deltas resume.</p></div></div></section>
    <section><ObjectLabel>DELIVERY</ObjectLabel><h2>Ordered deltas, defensive consumers</h2><p>Beta-0 delivers contiguous WebSocket deltas only after accepting the current REST snapshot position and matching scope. Consumers should deduplicate by message ID and make full-state replacements idempotent.</p><FieldTable rows={[["message_id","deduplication","UUID for one emitted message."],["sequence","ordering","Per-subscription ordering; the first relevant delta is 1."],["effective_scope","ownership","Prevents data outside the accepted filters from entering state."],["schema_version","compatibility","Every REST body and WebSocket envelope declares version 1."]]} /></section>
    <section><ObjectLabel>TIME</ObjectLabel><h2>Three relevant clocks</h2><FieldTable rows={[["observedAt","RFC 3339","When OddsLoom observed the provider state."],["emitted_at","RFC 3339","When OddsLoom published the snapshot or frame."],["consumer_received_at","client clock","When your system received the frame; recorded by the consumer."]]} /><p>Use sequence for ordering. Use timestamps for freshness analysis. Provider clocks may be absent or skewed and are never invented.</p></section>
    <section><ObjectLabel>STATE</ObjectLabel><h2>Quote availability</h2><div className="state-lanes"><div><b>OPEN</b><span>Quote may be consumed as current.</span></div><i>→</i><div><b>SUSPENDED</b><span>Retain the last quote but treat it as unavailable.</span></div><i>→</i><div><b>OPEN</b><span>The same quote ID may reopen with replacement state.</span></div></div><div className="state-lanes"><div><b>OPEN</b><span>Current offer exists.</span></div><i>→</i><div><b>CLOSED</b><span>Market or event reached a terminal condition.</span></div><i>→</i><div><b>REMOVED</b><span>Delete after an explicit <code>odds.remove</code>.</span></div></div><p>A correction is a replacement upsert at a higher sequence. Provider degradation is explicit, and last-known values are not presented as current after the freshness threshold.</p></section>
    <section><ObjectLabel>RECOVERY</ObjectLabel><h2>Reconnect and gap procedure</h2><div className="flow-row"><span>RECONNECT OR GAP</span><i>→</i><span>PAUSE DELTAS</span><i>→</i><span>FRESH REST SNAPSHOT</span><i>→</i><span>NEW SUBSCRIPTION</span><i>→</i><span>DECLARE POSITION</span><i>→</i><span>RESUME</span></div><ol><li>Stop mutating consumer-visible state when the connection closes or the next sequence is missing.</li><li>Discard uncommitted deltas and atomically replace state with a fresh filtered REST snapshot.</li><li>Open a new authenticated subscription with that snapshot’s position and matching filters.</li><li>Resume only after the server accepts the current position.</li></ol><p>There is no beta replay, backfill, historical API, or resume-from-committed-position path. A stale position is rejected with <code>fresh_snapshot_required</code>.</p></section>
    <section><ObjectLabel>OPERATIONS / CANDIDATE SLOS</ObjectLabel><h2>Targets to validate, not promises</h2><p>These are candidate beta SLOs. They guide implementation and measurement, but are not customer commitments until measured and published as such.</p><div className="payload-matrix"><div><code>processing freshness</code><span>p95 ≤ 2 seconds from source receipt to customer publication while the source connection is healthy.</span><b>CANDIDATE</b></div><div><code>stale-state detection</code><span>Mark a supported source degraded within 15 seconds of exceeding its source-specific heartbeat or refresh threshold.</span><b>CANDIDATE</b></div><div><code>delivery availability</code><span>99.5% monthly for snapshot and stream endpoints, excluding announced maintenance and upstream sportsbook outages.</span><b>CANDIDATE</b></div><div><code>recovery</code><span>Obtain a coherent snapshot and stream position within 10 seconds at the documented beta scope.</span><b>CANDIDATE</b></div><div><code>correctness</code><span>No known silent sequence gaps; corrections and removals are explicit and ordered.</span><b>CANDIDATE</b></div></div><p>Upstream sportsbook availability is measured separately from OddsLoom delivery availability. No source-to-OddsLoom latency promise is made when a trustworthy source timestamp is unavailable.</p></section>
    <section className="docs-cta"><h2>Tell us where this breaks.</h2><p>We want concrete feedback about sequence scope, fresh-snapshot recovery, market identity, and state transitions while the implementation is validated.</p><a className="button primary" href="/beta">Request beta access →</a></section>
  </DocsPage>
}
